### PR TITLE
maintenance cycle

### PR DESCRIPTION
**Pull request by supakeen**
Doing a maintenance cycle on this repository, it's sorely needed.

### CODE REVIEW

**Comment by supakeen** [comment]
There are two main issues left over:

- We copy all repositories that are available in `osbuild-composer/repositories` into its config in the container, this includes a repository called `rhel-8-beta` that is an invalid name after dot notation.
- `osbuild-composer` checks if there are two sockets configured in its systemd unit file. We don't run `osbuild-composer` through systemd; this check fails.

**Comment by supakeen** [comment]
This branch now works for me locally so it is ready for review.

**Comment by elkoniu** [comment]
@schuellerf in the draft PR I saw you will be doing serious rework in this repo. I am wondering if this will overwrite changes in this PR or should be placed on top of those?

**Comment by schuellerf** [comment]
@elkoniu no I'll integrate this one or rebase - let's see - I'm aware of this PR

**Pull request merged**
